name: "Bump Version"

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: Bump version (${{ github.sha }})
    runs-on: ubuntu-latest

    steps:
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Semantic Release
          uses: cycjimmy/semantic-release-action@v2
          with:
            semantic_version: 16
            extra_plugins: |
              @semantic-release/changelog@3.0.0
              @semantic-release/git
            branches: |    
              [
                'master', 
                'next', 
                'next-major', 
                {
                  name: 'beta', 
                  prerelease: true
                }, 
                {
                  name: 'alpha', 
                  prerelease: true
                }
              ]
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}