name: "Bump Version"

on:
#  pull_request:
#    branches:
#      - master
#      - develop
  push:
    branches:
      - master
#      - develop

jobs:
  bump-version:
    name: Bump version (${{ github.sha }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 16
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}