name: Publish

on: [push]
#  push:
#    tags:
#      - 'v*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: .exe
            asset_name: openworld-desktop.exe

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: openworld-desktop/package.json

    - name: Install
      working-directory: openworld-desktop
      run: npm install

    - name: Build
      working-directory: openworld-desktop
      run: npm run build

    - name: Upload binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: openworld-desktop/dist/openworld-desktop-${{ steps.package-version.outputs.current-version }}${{ matrix.artifact_name }}
        asset_name: openworld-desktop-${{ steps.package-version.outputs.current-version }}${{ matrix.artifact_name }}
        tag: ${{ github.ref }}
